# Generated by Django 3.0.3 on 2020-02-24 23:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('pub_date', models.DateField()),
                ('body', models.TextField()),
                ('url', models.URLField()),
                ('image', models.ImageField(upload_to='images/')),
                ('icon', models.ImageField(upload_to='image/')),
                ('votes_total', models.ImageField(default=1, upload_to='')),
                ('founder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
